### ISSUE TITLE
使用 Github Action CI 功能自动构建插件

### ISSUE THREAD

**Issue by Zam-0703** [b9891796435/diana_chrome_extension#3]
可以使用 Github 提供的 Action CI 功能构建插件，用户可以直接从 Release 中下载打包好的 Zip 包进行安装。

**Comment by Zam-0703** [comment]
> Github Action 使用教程: http://www.ruanyifeng.com/blog/2019/09/getting-started-with-github-actions.html

合入 #4 之后，在项目设置中设置 secrets 环境变量 REPO_TOKEN 为自己生成的 github token(需要勾选所有repo权限)，并且新建一个 `release` 分支并推送到远程即可。不创建 release 分支会在当前 master 分支上一直做 CI。

**Comment by b9891796435** [comment]
万分感谢！已经成功合入主分支。
