### ISSUE TITLE
Bug: 使用插件后, Chrome的原有的网页收藏夹被覆盖了, 请问如何解决啊?

### ISSUE THREAD

**Issue by Ricardo-Charles** [b9891796435/diana_chrome_extension#8]
![image](https://user-images.githubusercontent.com/44394716/173583062-f2634526-dae7-447f-a4a7-8200a5a5dd56.png)
![image](https://user-images.githubusercontent.com/44394716/173583874-cf15326f-2e88-44ad-beed-978a5b8433f8.png)

> **操作系统**: win10
**最新版Chrome**

**Comment by Ricardo-Charles** [comment]
> ![image](https://user-images.githubusercontent.com/44394716/173583062-f2634526-dae7-447f-a4a7-8200a5a5dd56.png) ![image](https://user-images.githubusercontent.com/44394716/173583874-cf15326f-2e88-44ad-beed-978a5b8433f8.png)
> 
> > **操作系统**: win10
> > **最新版Chrome**

应该是我自己电脑的问题 , 因为我看作者您的视频里面, 可以正常显示这些

**Comment by Ricardo-Charles** [comment]
我自己去解决一下, 因为作者您那边可以正常显示网址收藏夹, 这不是您代码的问题

**Comment by b9891796435** [comment]
小伙伴你好，插件中甚至没有申请有关浏览器主题的权限哦。这里的书签栏可以在这里勾选“显示书签栏”来展示。
![新建位图图像](https://user-images.githubusercontent.com/76828507/173595948-aea8435f-108e-433d-9ac3-98fd8f770ed0.jpg)

**Comment by Ricardo-Charles** [comment]
> 小伙伴你好，插件中甚至没有申请有关浏览器主题的权限哦。这里的书签栏可以在这里勾选“显示书签栏”来展示。 ![新建位图图像](https://user-images.githubusercontent.com/76828507/173595948-aea8435f-108e-433d-9ac3-98fd8f770ed0.jpg)

谢谢您, 按照您的方法已经解决了
